"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { OrderRecord, OrderStatus } from "./types";
import { fetchOrders } from "../lib/orders-client";
import AppNav from "./AppNav";
import "../operations-flow.css";

const statusLabel:Record<OrderStatus,string>={submitted:"접수",confirmed:"작업 대기",in_progress:"작업 중",ready:"준비 완료",fulfilled:"전달 완료",cancelled:"취소"};
const won=(value:number)=>value.toLocaleString("ko-KR")+"원";
const todayInSeoul=()=>{const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),part=(type:string)=>parts.find(value=>value.type===type)?.value??"";return `${part("year")}-${part("month")}-${part("day")}`};

export default function AdminApp(){
 const[view,setView]=useState<"home"|"search"|"pickup"|"shipping">("home"),[orders,setOrders]=useState<OrderRecord[]>([]),[query,setQuery]=useState(""),[selectedDate,setSelectedDate]=useState(todayInSeoul),[error,setError]=useState(""),[notice,setNotice]=useState(""),[refreshing,setRefreshing]=useState(false),[lastSync,setLastSync]=useState("");
 const currentQuery=useCallback(()=>({q:view==="search"?query:"",date:view==="pickup"||view==="shipping"?selectedDate:""}),[query,selectedDate,view]);
 const load=useCallback(async(options?:{silent?:boolean})=>{if(!options?.silent)setRefreshing(true);try{setOrders(await fetchOrders(currentQuery()));setError("");setLastSync(new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date()))}catch(caught){setError(caught instanceof Error?caught.message:"주문을 불러오지 못했습니다.")}finally{setRefreshing(false)}},[currentQuery]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{void load()}),timer=setInterval(()=>{void load({silent:true})},2500),sync=()=>void load({silent:true});window.addEventListener("focus",sync);window.addEventListener("online",sync);return()=>{cancelAnimationFrame(frame);clearInterval(timer);window.removeEventListener("focus",sync);window.removeEventListener("online",sync)}},[load]);
 const update=async(order:OrderRecord,status:"confirmed"|"fulfilled")=>{const response=await fetch("/api/orders/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:order.id,status,expectedVersion:order.version})}),data=await response.json() as {error?:string};if(!response.ok){setNotice(data.error??"상태를 변경하지 못했습니다.");return}setNotice(status==="confirmed"?"주문을 확인하고 작업장에 전달했습니다.":"고객 전달을 완료했습니다.");await load()};
 const list=useMemo(()=>orders.filter(order=>view==="pickup"?order.fulfillmentType==="pickup"&&order.status!=="fulfilled":view==="shipping"?order.fulfillmentType==="shipping"&&order.status!=="fulfilled":true),[orders,view]),submittedOrders=useMemo(()=>orders.filter(order=>order.status==="submitted"),[orders]),missingAddress=useMemo(()=>orders.filter(order=>order.fulfillmentType==="shipping"&&(!order.roadAddress||!order.postalCode)),[orders]);
 return <div className="ops-app"><header className="ops-header"><a href="/admin" className="ops-brand"><b>正</b><span>정일품 주문관리<small>판매장</small></span></a><AppNav current="admin"/><div className="ops-alerts"><button onClick={()=>void load()} disabled={refreshing}>{refreshing?"동기화 중…":"새로고침"}</button><a href="/signout-with-chatgpt?return_to=/">로그아웃</a></div></header>
  <main className="ops-main">{view==="home"?<><div className="ops-welcome"><small>2026 추석 · 실제 주문 데이터</small><h1>무엇을 도와드릴까요?</h1><p>최근 동기화 {lastSync||"준비 중"} · 최대 3초 간격 자동 반영</p></div><div className="task-buttons"><button onClick={()=>setView("search")}><span>⌕</span><div><b>주문 찾기</b><small>이름·전화번호·주문번호로 찾기</small></div><i>→</i></button><a href="/kiosk"><span>＋</span><div><b>주문 받기</b><small>판매장에서 새 주문 접수</small></div><i>→</i></a><button onClick={()=>setView("pickup")}><span>♧</span><div><b>상품 찾아가기</b><small>날짜별 방문수령 주문 확인</small></div><i>→</i></button><button onClick={()=>setView("shipping")}><span>▣</span><div><b>보낼 상품</b><small>발송일별 주소와 준비상태 확인</small></div><i>→</i></button></div><section className="attention"><h2>실제 주문 확인사항</h2>{submittedOrders.length?<button onClick={()=>setView("search")}><span className="warning">{submittedOrders.length}</span><div><b>확인 대기 주문 {submittedOrders.length}건</b><small>접수된 실제 주문입니다.</small></div><i>→</i></button>:<p className="ops-clear">현재 확인 대기 주문이 없습니다.</p>}{missingAddress.length?<button onClick={()=>setView("shipping")}><span className="critical">{missingAddress.length}</span><div><b>주소 확인 필요 {missingAddress.length}건</b><small>실제 배송 주문의 주소를 확인해주세요.</small></div><i>→</i></button>:null}</section><section className="recent-orders"><header><div><small>LIVE ORDERS · D1</small><h2>접수된 주문 <b>{submittedOrders.length}</b></h2></div><button onClick={()=>void load()} disabled={refreshing}>지금 새로고침</button></header><div className="admin-order-list">{submittedOrders.length?submittedOrders.slice(0,5).map(order=><OrderCard key={order.id} order={order} update={update}/>):<div className="empty-orders">새로 접수된 주문이 없습니다.</div>}</div></section></>:<OrderWorkspace view={view} setView={setView} list={list} query={query} setQuery={setQuery} selectedDate={selectedDate} setSelectedDate={setSelectedDate} search={()=>void load()} update={update} refresh={()=>void load()} refreshing={refreshing}/>}
  {error&&<div className="access-error"><b>운영 화면에 연결할 수 없습니다</b><span>{error}</span><a href="/signin-with-chatgpt?return_to=/admin">운영자 로그인</a></div>}{notice&&<div className="ops-toast" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="알림 닫기">×</button></div>}</main>
  <nav className="bottom-nav"><button className={view==="home"?"active":""} onClick={()=>setView("home")}><span>⌂</span>홈</button><button className={view==="search"?"active":""} onClick={()=>setView("search")}><span>⌕</span>주문</button><button className={view==="pickup"?"active":""} onClick={()=>setView("pickup")}><span>♧</span>방문수령</button><button className={view==="shipping"?"active":""} onClick={()=>setView("shipping")}><span>▣</span>배송</button><button onClick={()=>void load()}><span>↻</span>새로고침</button></nav>
 </div>;
}
function OrderCard({order,update}:{order:OrderRecord;update:(order:OrderRecord,status:"confirmed"|"fulfilled")=>void}){
 return <article className="admin-order-card"><header><span><small>{order.orderNo}</small><b>{order.buyerName}</b></span><em className={"state "+order.status}>{statusLabel[order.status]}</em></header><div className="order-card-body"><p><span>상품</span><b>{order.items.map(item=>item.name+" × "+item.quantity).join(", ")}</b></p><p><span>받는 방법</span><b>{order.fulfillmentType==="pickup"?"방문수령":"택배발송"}</b></p><p><span>일정</span><b>{order.scheduleLabel}</b></p><p><span>주문금액</span><b>{won(order.totalAmount)}</b></p>{order.fulfillmentType==="shipping"&&<><p><span>우편번호</span><b>{order.postalCode||"확인 필요"}</b></p><p><span>주소</span><b>{order.roadAddress||"주소 미입력"} {order.detailAddress}</b></p></>}</div><footer>{order.status==="submitted"&&<button className="task-primary" onClick={()=>update(order,"confirmed")}>주문 확인 · 작업장 전달</button>}{order.status==="ready"&&order.fulfillmentType==="pickup"&&<button className="task-primary" onClick={()=>update(order,"fulfilled")}>전달 완료</button>}</footer></article>;
}
function OrderWorkspace({view,setView,list,query,setQuery,selectedDate,setSelectedDate,search,update,refresh,refreshing}:{view:"search"|"pickup"|"shipping";setView:(value:"home"|"search"|"pickup"|"shipping")=>void;list:OrderRecord[];query:string;setQuery:(value:string)=>void;selectedDate:string;setSelectedDate:(value:string)=>void;search:()=>void;update:(order:OrderRecord,status:"confirmed"|"fulfilled")=>void;refresh:()=>void;refreshing:boolean}){
 const title=view==="search"?"주문 찾기":view==="pickup"?"상품 찾아가기":"보낼 상품";
 return <section className="order-workspace"><button className="back-home" onClick={()=>setView("home")}>← 홈으로</button><div className="workspace-title"><small>현장 업무</small><h1>{title}</h1><p>{view==="pickup"?"선택한 날짜의 방문 시간을 확인합니다.":view==="shipping"?"선택한 발송일의 주소와 준비 상태를 확인합니다.":"고객 정보 또는 주문번호를 입력해주세요."}</p></div>{view==="search"?<div className="order-search"><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>event.key==="Enter"&&search()} placeholder="이름, 전화번호, 주문번호, 수령인"/><button onClick={search}>검색</button></div>:<div className="sales-date-filter"><label><span>조회 날짜</span><input type="date" value={selectedDate} onChange={event=>setSelectedDate(event.target.value)}/></label><button onClick={refresh} disabled={refreshing}>{refreshing?"조회 중…":"새로고침"}</button></div>}<div className="admin-order-list">{list.length?list.map(order=><OrderCard key={order.id} order={order} update={update}/>):<div className="empty-orders">해당 날짜에 주문이 없습니다.</div>}</div></section>;
}
