"use client";
import { useEffect, useMemo, useState } from "react";
import type { OrderRecord, OrderStatus } from "./types";
import AppNav from "./AppNav";

const statusLabel:Record<OrderStatus,string>={submitted:"접수",confirmed:"작업 대기",in_progress:"작업 중",ready:"준비 완료",fulfilled:"전달 완료",cancelled:"취소"};
const won=(n:number)=>n.toLocaleString("ko-KR")+"원";

export default function AdminApp(){
 const[view,setView]=useState<"home"|"search"|"pickup"|"shipping">("home"),[orders,setOrders]=useState<OrderRecord[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async(q="")=>{try{const r=await fetch("/api/orders"+(q?"?q="+encodeURIComponent(q):""),{cache:"no-store"}),x=await r.json() as {orders?:OrderRecord[];error?:string};if(!r.ok)throw new Error(x.error);setOrders(x.orders??[]);setError("")}catch(e){setError(e instanceof Error?e.message:"주문을 불러오지 못했습니다.")}};
 useEffect(()=>{const frame=requestAnimationFrame(()=>{void load()});return()=>cancelAnimationFrame(frame)},[]);
 const update=async(o:OrderRecord,status:"confirmed"|"fulfilled")=>{const r=await fetch("/api/orders/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:o.id,status,expectedVersion:o.version})}),x=await r.json() as {error?:string};if(!r.ok){setNotice(x.error??"상태를 변경하지 못했습니다.");return}setNotice(status==="confirmed"?"주문을 확인하고 작업장에 전달했습니다.":"고객 전달을 완료했습니다.");load(query)};
 const list=useMemo(()=>orders.filter(o=>view==="pickup"?o.fulfillmentType==="pickup"&&o.status!=="fulfilled":view==="shipping"?o.fulfillmentType==="shipping"&&o.status!=="fulfilled":true),[orders,view]);
 return <div className="ops-app"><header className="ops-header"><a href="/admin" className="ops-brand"><b>正</b><span>정일품 주문관리<small>판매장</small></span></a><AppNav current="admin"/><div className="ops-alerts"><button>주문변경 <b>2</b></button><button>고객도착 <b>1</b></button><a href="/signout-with-chatgpt?return_to=/">로그아웃</a></div></header>
  <main className="ops-main">{view==="home"?<><div className="ops-welcome"><small>2026 추석 · 오늘의 업무</small><h1>무엇을 도와드릴까요?</h1><p>현장에서 바로 처리할 업무를 선택해주세요.</p></div><div className="task-buttons"><button onClick={()=>setView("search")}><span>⌕</span><div><b>주문 찾기</b><small>이름·전화번호·주문번호로 찾기</small></div><i>→</i></button><a href="/kiosk"><span>＋</span><div><b>주문 받기</b><small>판매장에서 새 주문 접수</small></div><i>→</i></a><button onClick={()=>setView("pickup")}><span>♧</span><div><b>상품 찾아가기</b><small>방문 고객의 준비 상품 확인</small></div><i>→</i></button><button onClick={()=>setView("shipping")}><span>▣</span><div><b>오늘 보낼 상품</b><small>주소와 준비상태 최종 확인</small></div><i>→</i></button></div><section className="attention"><h2>지금 확인해주세요</h2><button><span className="critical">!</span><div><b>작업 중 주문변경 1건</b><small>작업장 확인을 기다리고 있습니다.</small></div><i>→</i></button><button><span className="warning">⌖</span><div><b>주소 미입력 배송 3건</b><small>출고 전에 주소를 확인해주세요.</small></div><i>→</i></button></section></>:<OrderWorkspace view={view} setView={setView} list={list} query={query} setQuery={setQuery} search={()=>load(query)} update={update}/>}
  {error&&<div className="access-error"><b>운영 화면에 연결할 수 없습니다</b><span>{error}</span><a href="/signin-with-chatgpt?return_to=/admin">운영자 로그인</a></div>}{notice&&<div className="ops-toast" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="알림 닫기">×</button></div>}</main>
  <nav className="bottom-nav"><button className={view==="home"?"active":""} onClick={()=>setView("home")}><span>⌂</span>홈</button><button className={view==="search"?"active":""} onClick={()=>setView("search")}><span>⌕</span>주문</button><button className={view==="pickup"?"active":""} onClick={()=>setView("pickup")}><span>♧</span>방문수령</button><button className={view==="shipping"?"active":""} onClick={()=>setView("shipping")}><span>▣</span>배송</button><button><span>•••</span>더보기</button></nav>
 </div>
}
function OrderWorkspace({view,setView,list,query,setQuery,search,update}:{view:string;setView:(v:"home"|"search"|"pickup"|"shipping")=>void;list:OrderRecord[];query:string;setQuery:(v:string)=>void;search:()=>void;update:(o:OrderRecord,s:"confirmed"|"fulfilled")=>void}){
 const title=view==="search"?"주문 찾기":view==="pickup"?"상품 찾아가기":"오늘 보낼 상품";
 return <section className="order-workspace"><button className="back-home" onClick={()=>setView("home")}>← 홈으로</button><div className="workspace-title"><small>현장 업무</small><h1>{title}</h1><p>{view==="pickup"?"방문 시간순으로 준비 상태를 확인합니다.":view==="shipping"?"주소와 출고 준비 상태를 확인합니다.":"고객 정보 또는 주문번호를 입력해주세요."}</p></div>{view==="search"&&<div className="order-search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="이름, 전화번호 끝 4자리, 주문번호, 수령인"/><button onClick={search}>검색</button></div>}<div className="admin-order-list">{list.length?list.map(o=><article key={o.id} className="admin-order-card"><header><span><small>{o.orderNo}</small><b>{o.buyerName}</b></span><em className={"state "+o.status}>{statusLabel[o.status]}</em></header><div className="order-card-body"><p><span>상품</span><b>{o.items.map(i=>i.name+" × "+i.quantity).join(", ")}</b></p><p><span>받는 방법</span><b>{o.fulfillmentType==="pickup"?"방문수령":"택배발송"}</b></p><p><span>예정</span><b>{o.scheduleLabel}</b></p>{view==="search"&&<p><span>연락처</span><b>{o.buyerPhone}</b></p>}{o.fulfillmentType==="shipping"&&<p><span>주소</span><b>{o.roadAddress||"주소 미입력"} {o.detailAddress}</b></p>}<p><span>주문금액</span><b>{won(o.totalAmount)}</b></p></div><footer>{o.status==="submitted"&&<button className="task-primary" onClick={()=>update(o,"confirmed")}>주문 확인</button>}{o.status==="ready"&&o.fulfillmentType==="pickup"&&<button className="task-primary" onClick={()=>update(o,"fulfilled")}>찾으러 왔어요 · 전달완료</button>}<button>주문 상세</button><button>⋯</button></footer></article>):<div className="empty-orders">해당하는 주문이 없습니다.</div>}</div></section>
}
