"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { OrderRecord, OrderStatus } from "./types";
import { fetchOrders } from "../lib/orders-client";
import AppNav from "./AppNav";
import "../operations-flow.css";

const statusLabel:Record<OrderStatus,string>={submitted:"판매장 확인",confirmed:"대기",in_progress:"작업 중",ready:"완료",fulfilled:"전달됨",cancelled:"취소"};
export default function WorkshopApp(){
 const[orders,setOrders]=useState<OrderRecord[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async(silent=false)=>{if(!silent)setRefreshing(true);try{const result=await fetchOrders();setOrders(result.filter(order=>["submitted","confirmed","in_progress","ready"].includes(order.status)));setError("")}catch(caught){setError(caught instanceof Error?caught.message:"작업 목록을 불러오지 못했습니다.")}finally{setRefreshing(false)}},[]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{void load()}),timer=setInterval(()=>{void load(true)},2500),sync=()=>void load(true);window.addEventListener("focus",sync);window.addEventListener("online",sync);return()=>{cancelAnimationFrame(frame);clearInterval(timer);window.removeEventListener("focus",sync);window.removeEventListener("online",sync)}},[load]);
 const update=async(order:OrderRecord,status:"in_progress"|"ready")=>{const response=await fetch("/api/orders/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:order.id,status,expectedVersion:order.version})}),data=await response.json() as {error?:string};if(!response.ok){setNotice(data.error??"상태를 변경하지 못했습니다.");return}setNotice(status==="in_progress"?"작업을 시작했습니다.":"준비 완료로 표시했습니다.");await load()};
 const arrivals=useMemo(()=>orders.filter(order=>order.customerArrived),[orders]);
 return <div className="work-app"><header className="work-header"><div><small>WORKSHOP · LIVE D1</small><h1>오늘 작업</h1><p>실제 주문을 최대 3초 간격으로 동기화합니다.</p></div><div className="work-tools"><AppNav current="workshop"/><button className="sync-state" onClick={()=>void load()} disabled={refreshing}><i/>{refreshing?"동기화 중…":"지금 새로고침"}</button></div></header>{arrivals.length>0&&<section className="actual-arrivals">{arrivals.map(order=><div className="arrival-alert" key={order.id}><span>!</span><div><small>고객 도착</small><h2>{order.buyerName} 고객님</h2><p>{order.items.map(item=>`${item.name} ${item.quantity}`).join(" · ")}</p></div><button>확인 필요</button></div>)}</section>}<div className="work-list">{orders.map((order,index)=><article className={"work-order "+(index===0?"priority":"")} key={order.id}>{index===0&&<header>가장 먼저 준비해주세요</header>}<div className="work-order-head"><span><small>{order.fulfillmentType==="pickup"?order.scheduleLabel:"배송 · "+order.scheduleLabel}</small><h2>{order.buyerName}</h2></span><em className={"state "+order.status}>{statusLabel[order.status]}</em></div><div className="work-products">{order.items.map(item=><p key={item.id}><span>正</span><b>{item.name}<small>{item.quantity}세트 · 개별 포장</small></b><strong>× {item.quantity}</strong></p>)}</div>{order.note&&<div className="work-request"><span>요청</span><b>{order.note}</b></div>}<div className="work-labels"><span>라벨</span>{order.packageCodes.length?order.packageCodes.map(code=><code key={code}>{code}</code>):<small>주문 확인 후 생성</small>}</div>{order.status==="submitted"&&<button className="work-action awaiting" disabled>판매장 주문 확인 대기</button>}{order.status==="confirmed"&&<button className="work-action" onClick={()=>update(order,"in_progress")}>작업 시작 <span>→</span></button>}{order.status==="in_progress"&&<button className="work-action complete" onClick={()=>update(order,"ready")}>작업 완료 <span>✓</span></button>}{order.status==="ready"&&<button className="work-action done" disabled>준비 완료됨 ✓</button>}</article>)}</div>{!orders.length&&!error&&<div className="empty-work">현재 대기 중인 실제 주문이 없습니다.</div>}{error&&<div className="access-error"><b>작업 목록에 연결할 수 없습니다</b><span>{error}</span><a href="/signin-with-chatgpt?return_to=/workshop">작업자 로그인</a></div>}{notice&&<div className="ops-toast" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="알림 닫기">×</button></div>}<nav className="work-bottom"><button className="active"><span>▤</span>오늘 작업</button><button><span>▦</span>상품별</button><button><span>□</span>가용품</button><button onClick={()=>void load()}><span>↻</span>새로고침</button></nav></div>;
}
