"use client";
import { useEffect, useState } from "react";
import type { OrderRecord, OrderStatus } from "./types";
import AppNav from "./AppNav";
const statusLabel:Record<OrderStatus,string>={submitted:"판매장 확인",confirmed:"대기",in_progress:"작업 중",ready:"완료",fulfilled:"전달됨",cancelled:"취소"};
export default function WorkshopApp(){
 const[orders,setOrders]=useState<OrderRecord[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{try{const r=await fetch("/api/orders",{cache:"no-store"}),x=await r.json() as {orders?:OrderRecord[];error?:string};if(!r.ok)throw new Error(x.error);setOrders((x.orders??[]).filter((o:OrderRecord)=>["confirmed","in_progress","ready"].includes(o.status)));setError("")}catch(e){setError(e instanceof Error?e.message:"작업 목록을 불러오지 못했습니다.")}};
 useEffect(()=>{const frame=requestAnimationFrame(()=>{void load()});const timer=setInterval(()=>{void load()},8000);return()=>{cancelAnimationFrame(frame);clearInterval(timer)}},[]);
 const update=async(o:OrderRecord,status:"in_progress"|"ready")=>{const r=await fetch("/api/orders/status",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:o.id,status,expectedVersion:o.version})}),x=await r.json() as {error?:string};if(!r.ok){setNotice(x.error??"상태를 변경하지 못했습니다.");return}setNotice(status==="in_progress"?"작업을 시작했습니다.":"준비 완료로 표시했습니다.");load()};
 return <div className="work-app"><header className="work-header"><div><small>WORKSHOP · LIVE</small><h1>오늘 작업</h1><p>방문과 배송 일정이 가까운 순서입니다.</p></div><div className="work-tools"><AppNav current="workshop"/><div className="sync-state"><i/>8초마다 자동 동기화</div></div></header><section className="emergency-bar"><button><span>🚨</span><b>고객도착 <em>1</em></b></button><button><span>!</span><b>주문변경 <em>2</em></b></button><button><span>▧</span><b>라벨조치 <em>1</em></b></button></section><section className="arrival-alert"><span>🚨</span><div><small>고객 도착</small><h2>김철수 고객님</h2><p>봉황세트 2 · 요청: 지방 적게</p></div><button>확인했습니다</button></section><div className="work-list">{orders.map((o,i)=><article className={"work-order "+(i===0?"priority":"")} key={o.id}>{i===0&&<header>가장 먼저 준비해주세요</header>}<div className="work-order-head"><span><small>{o.fulfillmentType==="pickup"?o.scheduleLabel:"배송 · "+o.scheduleLabel}</small><h2>{o.buyerName}</h2></span><em className={"state "+o.status}>{statusLabel[o.status]}</em></div><div className="work-products">{o.items.map(item=><p key={item.id}><span>正</span><b>{item.name}<small>{item.quantity}세트 · 개별 포장</small></b><strong>× {item.quantity}</strong></p>)}</div>{o.note&&<div className="work-request"><span>요청</span><b>{o.note}</b></div>}<div className="work-labels"><span>라벨</span>{o.packageCodes.length?o.packageCodes.map(code=><code key={code}>{code}</code>):<small>주문 확인 후 생성</small>}</div>{o.status==="confirmed"&&<button className="work-action" onClick={()=>update(o,"in_progress")}>작업 시작 <span>→</span></button>}{o.status==="in_progress"&&<button className="work-action complete" onClick={()=>update(o,"ready")}>작업 완료 <span>✓</span></button>}{o.status==="ready"&&<button className="work-action done" disabled>준비 완료됨 ✓</button>}</article>)}</div>{!orders.length&&!error&&<div className="empty-work">현재 대기 중인 작업이 없습니다.</div>}{error&&<div className="access-error"><b>작업 목록에 연결할 수 없습니다</b><span>{error}</span><a href="/signin-with-chatgpt?return_to=/workshop">작업자 로그인</a></div>}{notice&&<div className="ops-toast" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="알림 닫기">×</button></div>}<nav className="work-bottom"><button className="active"><span>▤</span>오늘 작업</button><button><span>▦</span>상품별</button><button><span>□</span>가용품</button><button><span>•••</span>더보기</button></nav></div>
}
