"use client";
import {useEffect,useState} from "react";

type Mode="kiosk"|"admin"|"workshop";
type Status="submitted"|"confirmed"|"working"|"ready"|"fulfilled";
type Product={id:string;category:string;name:string;subtitle:string;price:number;badge?:string;tone:string};
type Order={id:string;orderNo:string;buyer:string;phone:string;items:{id:string;name:string;qty:number;price:number}[];total:number;fulfillment:"pickup"|"shipping";schedule:string;note:string;status:Status;time:string;labels:string[]};

const products:Product[]=[
{id:"bh",category:"진공세트",name:"봉황세트",subtitle:"정일품의 대표 명절 구성",price:200000,badge:"BEST",tone:"ruby"},
{id:"py",category:"진공세트",name:"팔영세트",subtitle:"감사의 마음을 더 풍성하게",price:300000,tone:"amber"},
{id:"jin",category:"프리미엄",name:"진(眞)",subtitle:"하루 20세트 한정",price:320000,badge:"PREMIUM",tone:"ink"},
{id:"sun",category:"프리미엄",name:"선(善)",subtitle:"하루 20세트 한정",price:270000,tone:"forest"},
{id:"mi",category:"프리미엄",name:"미(美)",subtitle:"하루 30세트 한정",price:220000,tone:"plum"},
{id:"la",category:"LA갈비",name:"LA갈비 1.8kg",subtitle:"미국산 Prime Excel · 900g×2",price:99000,badge:"실속",tone:"sand"}];

const initial:Order[]=[
{id:"1",orderNo:"JI-260822-0142",buyer:"김철수",phone:"010-4281-9053",items:[{id:"bh",name:"봉황세트",qty:2,price:200000}],total:400000,fulfillment:"pickup",schedule:"오늘 14:00–15:00",note:"도착 10분 전에 연락 부탁드립니다.",status:"confirmed",time:"09:18",labels:["BH-0142-01","BH-0142-02"]},
{id:"2",orderNo:"JI-260822-0141",buyer:"박영희",phone:"010-7702-1184",items:[{id:"la",name:"LA갈비 1.8kg",qty:1,price:99000}],total:99000,fulfillment:"pickup",schedule:"오늘 13:00–14:00",note:"",status:"working",time:"09:05",labels:["LA-0141-01"]},
{id:"3",orderNo:"JI-260822-0139",buyer:"이정호",phone:"010-3160-4477",items:[{id:"mi",name:"미(美)",qty:1,price:220000}],total:220000,fulfillment:"shipping",schedule:"8월 24일 출고",note:"경비실에 맡겨주세요.",status:"ready",time:"08:42",labels:["MI-0139-01"]}];

const sm:Record<Status,[string,string]>={submitted:["접수","blue"],confirmed:["확인 완료","violet"],working:["작업 중","orange"],ready:["준비 완료","green"],fulfilled:["수령 완료","gray"]};
const won=(n:number)=>n.toLocaleString("ko-KR")+"원";
const Brand=({full=true}:{full?:boolean})=><div className="brand"><b>正</b><strong>정일품</strong>{full&&<span>명절 선물 예약</span>}</div>;

export default function Home(){
 const[mode,setMode]=useState<Mode>("kiosk"),[cart,setCart]=useState<Record<string,number>>({}),[orders,setOrders]=useState<Order[]>(initial),[checkout,setCheckout]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{const x=localStorage.getItem("jeongilpum-orders");if(x)try{setOrders(JSON.parse(x))}catch{}},[]);
 useEffect(()=>localStorage.setItem("jeongilpum-orders",JSON.stringify(orders)),[orders]);
 const notice=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2400)};
 const status=(id:string,s:Status)=>{setOrders(a=>a.map(o=>o.id===id?{...o,status:s}:o));notice(s==="fulfilled"?"수령 완료로 처리했습니다.":"상태가 안전하게 반영되었습니다.")};
 return <main><header className="topbar"><Brand/><nav>{([["kiosk","고객 주문"],["admin","판매 관리"],["workshop","작업장"]] as [Mode,string][]).map(([v,l])=><button className={mode===v?"active":""} onClick={()=>setMode(v)} key={v}>{l}</button>)}</nav><div className="season"><i/>2026 추석 · 판매중</div></header>
 {mode==="kiosk"&&<Kiosk cart={cart} setCart={setCart} open={()=>setCheckout(true)}/>}
 {mode==="admin"&&<Admin orders={orders} status={status} go={setMode}/>}
 {mode==="workshop"&&<Workshop orders={orders} status={status}/>}
 {checkout&&<Checkout cart={cart} close={()=>setCheckout(false)} submit={o=>{setOrders(a=>[o,...a]);setCart({});setCheckout(false);notice("주문이 접수되었습니다 · "+o.orderNo)}}/>}
 {toast&&<div className="toast"><b>✓</b>{toast}</div>}
 </main>
}

function Kiosk({cart,setCart,open}:{cart:Record<string,number>;setCart:React.Dispatch<React.SetStateAction<Record<string,number>>>;open:()=>void}){
 const[cat,setCat]=useState("전체"),list=cat==="전체"?products:products.filter(p=>p.category===cat);
 const qty=Object.values(cart).reduce((a,b)=>a+b,0),total=products.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0);
 const change=(id:string,n:number)=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+n)}));
 return <div className="kiosk"><section className="catalog"><div className="hero"><div><p className="eyebrow">2026 CHUSEOK COLLECTION</p><h1>소중한 분께 드리는<br/><em>정직한 한 상</em></h1><p>정일품이 엄선한 명절 선물세트를 예약하세요.<br/>포장부터 수령까지 정성껏 준비합니다.</p></div><div className="seal"><small>한가위</small><b>情</b><span>마음을 담다</span></div></div>
 <div className="heading"><div><small>STEP 1</small><h2>선물세트를 골라주세요</h2></div><span>가격은 부가세 포함입니다</span></div><div className="tabs">{["전체","진공세트","프리미엄","LA갈비"].map(c=><button className={cat===c?"active":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div>
 <div className="products">{list.map(p=>{const n=cart[p.id]||0;return <article className="product" key={p.id}><div className={"visual "+p.tone}><div className="gift"><i/><b>正</b><span/></div>{p.badge&&<label>{p.badge}</label>}<small>{p.category}</small></div><div className="info"><p>{p.category}</p><h3>{p.name}</h3><span>{p.subtitle}</span><footer><strong>{won(p.price)}</strong>{n?<div className="qty"><button onClick={()=>change(p.id,-1)}>−</button><b>{n}</b><button onClick={()=>change(p.id,1)}>＋</button></div>:<button className="add" onClick={()=>change(p.id,1)}>담기 <b>＋</b></button>}</footer></div></article>})}</div></section>
 <aside className="cart"><div className="carthead"><div><small>STEP 2</small><h2>주문 내역</h2></div><b>{qty}</b></div>{qty?<div className="cartitems">{products.filter(p=>cart[p.id]).map(p=><div key={p.id}><span><b>{p.name}</b><small>{won(p.price)} × {cart[p.id]}</small></span><strong>{won(p.price*cart[p.id])}</strong></div>)}</div>:<div className="empty"><b>福</b><h3>아직 담은 상품이 없어요</h3><p>마음을 전할 선물세트를<br/>골라주세요.</p></div>}<div className="summary"><div><span>상품 {qty}개</span><b>{won(total)}</b></div><p>방문수령 또는 택배를 다음 단계에서 선택할 수 있어요.</p><button className="primary" disabled={!qty} onClick={open}>수령 방법 선택하기 <span>→</span></button></div><div className="help"><b>☎</b><span><strong>주문이 어려우신가요?</strong><small>직원 호출 버튼을 눌러주세요.</small></span><button>직원 호출</button></div></aside></div>
}

function Checkout({cart,close,submit}:{cart:Record<string,number>;close:()=>void;submit:(o:Order)=>void}){
 const[buyer,setBuyer]=useState(""),[phone,setPhone]=useState(""),[way,setWay]=useState<"pickup"|"shipping">("pickup"),[schedule,setSchedule]=useState("오늘 16:00–17:00"),[note,setNote]=useState("");
 const items=products.filter(p=>cart[p.id]).map(p=>({id:p.id,name:p.name,qty:cart[p.id],price:p.price})),total=items.reduce((s,i)=>s+i.qty*i.price,0),valid=buyer.trim().length>1&&phone.replace(/\D/g,"").length>9;
 return <div className="backdrop" onMouseDown={close}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">STEP 3 · 주문 접수</p><h2>어떻게 받으실까요?</h2><div className="ways"><button className={way==="pickup"?"active":""} onClick={()=>setWay("pickup")}><b>⌂</b><strong>매장에서 받을게요</strong><span>원하는 시간에 빠르게 수령</span></button><button className={way==="shipping"?"active":""} onClick={()=>setWay("shipping")}><b>▣</b><strong>택배로 보낼게요</strong><span>안전 포장 후 지정일 출고</span></button></div><div className="form"><label>주문자 이름<input value={buyer} onChange={e=>setBuyer(e.target.value)} placeholder="예: 김정일"/></label><label>휴대폰 번호<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="010-0000-0000" inputMode="numeric"/></label><label className="wide">{way==="pickup"?"방문 예정 시간":"출고 희망일"}<select value={schedule} onChange={e=>setSchedule(e.target.value)}><option>오늘 16:00–17:00</option><option>내일 10:00–11:00</option><option>내일 14:00–15:00</option><option>8월 24일 출고</option></select></label><label className="wide">요청사항 <small>선택</small><input value={note} onChange={e=>setNote(e.target.value)} placeholder="예: 도착 전에 연락해주세요"/></label></div><div className="total"><span>결제 예정 금액</span><b>{won(total)}</b></div><button className="primary" disabled={!valid} onClick={()=>{const no=String(Date.now()).slice(-4);submit({id:crypto.randomUUID(),orderNo:"JI-260822-"+no,buyer:buyer.trim(),phone,items,total,fulfillment:way,schedule,note,status:"submitted",time:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}),labels:[]})}}>주문 접수하기 <span>→</span></button><p className="safe">버튼을 여러 번 눌러도 주문은 한 번만 접수되도록 보호됩니다.</p></section></div>
}

function Admin({orders,status,go}:{orders:Order[];status:(id:string,s:Status)=>void;go:(m:Mode)=>void}){
 const[filter,setFilter]=useState("all"),visible=orders.filter(o=>filter==="all"||o.fulfillment===filter);
 const metrics=[["▤","오늘 주문",orders.length,"건"],["⌂","방문 예정",orders.filter(o=>o.fulfillment==="pickup"&&o.status!=="fulfilled").length,"건"],["✓","작업 완료",orders.filter(o=>o.status==="ready").length,"건"],["₩","미수금","319,000","원"]];
 return <div className="dashboard"><aside className="sidebar"><Brand full={false}/><small>운영</small>{["▦  대시보드","⌕  주문 찾기","＋  새 주문","⌂  오늘 방문","▣  오늘 배송","◫  작업 현황"].map((x,i)=><button className={!i?"active":""} key={x}>{x}</button>)}<small>관리</small>{["·  상품 관리","·  시즌 관리","·  고객","·  통계 / Excel"].map(x=><button key={x}>{x}</button>)}<button className="preview" onClick={()=>go("kiosk")}>고객 화면 보기 ↗</button></aside><section className="dashmain"><div className="dashhead"><div><p className="eyebrow">SATURDAY · 2026.08.22</p><h1>좋은 아침이에요, <em>정일품</em> 님</h1><p>오늘도 정성스러운 선물을 준비해볼까요?</p></div><div className="profile"><b>♢</b><i>정</i><span>관리자<small>admin</small></span></div></div><div className="metrics">{metrics.map(m=><article key={String(m[1])}><b>{m[0]}</b><span>{m[1]}<strong>{m[2]}<small>{m[3]}</small></strong></span></article>)}</div><div className="operations"><section className="orders"><div className="panelhead"><span><h2>오늘 주문</h2><small>실시간으로 업데이트됩니다</small></span><button>전체보기 →</button></div><div className="filters">{[["all","전체"],["pickup","방문수령"],["shipping","택배"]].map(([v,l])=><button className={filter===v?"active":""} onClick={()=>setFilter(v)} key={v}>{l}</button>)}<label>⌕ <input placeholder="이름, 전화번호, 주문번호"/></label></div>{visible.map(o=><article className="order" key={o.id}><div className="time">{o.time}<small>{o.fulfillment==="pickup"?"방문":"택배"}</small></div><div><b>{o.buyer}</b><small>{o.phone}</small></div><div className="orderprod"><b>{o.items.map(i=>i.name).join(", ")}</b><small>{o.items.reduce((s,i)=>s+i.qty,0)}세트 · {won(o.total)}</small></div><div><small>예정</small><b>{o.schedule}</b></div><label className={"status "+sm[o.status][1]}>{sm[o.status][0]}</label><div className="actions">{o.status==="submitted"&&<button onClick={()=>status(o.id,"confirmed")}>주문 확인</button>}{o.status==="ready"&&o.fulfillment==="pickup"&&<button onClick={()=>status(o.id,"fulfilled")}>인계 완료</button>}<button>•••</button></div></article>)}</section><aside className="works"><div className="panelhead"><span><h2>작업 현황</h2><small>현재 준비 상태</small></span><button onClick={()=>go("workshop")}>작업장 →</button></div><div className="ring"><b>{Math.round(orders.filter(o=>["ready","fulfilled"].includes(o.status)).length/Math.max(orders.length,1)*100)}%</b><span>완료율</span></div><div className="legend"><p><i className="g"/>준비 완료 <b>{orders.filter(o=>o.status==="ready").length}</b></p><p><i className="o"/>작업 중 <b>{orders.filter(o=>o.status==="working").length}</b></p><p><i/>대기 <b>{orders.filter(o=>o.status==="confirmed").length}</b></p></div><div className="urgent"><b>!</b><span><strong>13시 방문이 가까워요</strong><small>박영희 · LA갈비 1.8kg</small></span></div></aside></div></section></div>
}

function Workshop({orders,status}:{orders:Order[];status:(id:string,s:Status)=>void}){
 const queue=orders.filter(o=>["confirmed","working","ready"].includes(o.status));
 return <div className="workshop"><div className="workhead"><span><p className="eyebrow">WORKSHOP · LIVE</p><h1>오늘의 작업</h1><p>방문 시간과 배송 일정을 기준으로 자동 정렬했습니다.</p></span><label><i/>실시간 연결됨</label></div><div className="workmetrics"><div><span>오늘 작업</span><b>{queue.reduce((s,o)=>s+o.items.reduce((a,i)=>a+i.qty,0),0)}<small>세트</small></b></div><div><span>작업 중</span><b>{queue.filter(o=>o.status==="working").length}<small>건</small></b></div><div><span>준비 완료</span><b>{queue.filter(o=>o.status==="ready").length}<small>건</small></b></div><div className="red"><span>긴급 알림</span><b>1<small>건</small></b></div></div><div className="worktoolbar"><span><button className="active">우선순위순</button><button>상품별 보기</button></span><small>변경된 주문은 확인 전까지 작업할 수 없습니다.</small></div><div className="workcards">{queue.map((o,i)=><article className={i===0?"urgentcard":""} key={o.id}>{i===0&&<header>방문 임박 · 우선 작업</header>}<div className="worktop"><span><i>{String(i+1).padStart(2,"0")}</i><b>{o.buyer}<small>{o.orderNo}</small></b></span><label className={"status "+sm[o.status][1]}>{sm[o.status][0]}</label></div><div className="workitems">{o.items.map(x=><div key={x.id}><i>正</i><span><b>{x.name}</b><small>{x.qty}세트 · 개별 포장</small></span><strong>× {x.qty}</strong></div>)}</div><div className="workmeta"><span><small>{o.fulfillment==="pickup"?"방문 시간":"출고 일정"}</small><b>{o.schedule}</b></span><span><small>요청사항</small><b>{o.note||"없음"}</b></span></div><div className="labels"><span>라벨</span>{o.labels.length?o.labels.map(x=><code key={x}>{x}</code>):<small>주문 확인 후 자동 생성</small>}</div>{o.status==="confirmed"&&<button className="primary" onClick={()=>status(o.id,"working")}>작업 시작 →</button>}{o.status==="working"&&<button className="primary" onClick={()=>status(o.id,"ready")}>작업 완료 ✓</button>}{o.status==="ready"&&<button className="done" disabled>준비 완료됨 ✓</button>}</article>)}</div></div>
}